- name: Manage Python application.
  hosts: localhost

  vars:
    image_name: "python-demo-app"
    image_tag: "v1"
    listen_port: "8080"
    build_dir: "./build"

  tasks:
    - name: Create build directory.
      file:
        path: "{{ build_dir }}"
        state: directory

    - name: Copy files.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: ../Dockerfile
          dest: "{{ build_dir }}"

        - src: ../app/requirements.txt
          dest: "{{ build_dir }}"

        - src: ../app/app.py
          dest: "{{ build_dir }}/app/"

        - src: ../app/app_test.py
          dest: "{{ build_dir }}/app/"

    - name: Build image.
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ build_dir }}"
        state: present
        push: true
        repository: "dvdty/ansible-python-app:{{ image_tag }}"

    - name: Run container.
      docker_container:
        name: run
        state: started
        image: "{{ image_name }}:{{ image_tag }}"
        ports:
          - "5001:5001"
        env:
          PORT: "5001"
