name: ci

on:
  push:
    branches: ['github-actions-practice']

jobs:
  editorconfig:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  linters:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      - name: black
        uses: psf/black@stable

      - name: markdown
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: README.md
          # config_file: .markdownlint.yaml
