name: ci

on:
  push:
    branches: ['github-actions-practice']

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check if editorconfig exists
        if: ${{ hashFiles('.editorconfig') == '' }}
        run: exit 'editorconfig does not exist.'

      - name: run editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@main
        run: editorconfig-checker

      - name: Run Python linter - pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      - name: Run Python linter - black
        uses: psf/black@stable

      - name: Run markdown linter
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: README.md

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        working-directory: ./app
        run: python -m pip install requirements.txt

  security:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
