name: ci

on:
  push:
    branches: ['github-actions-practice']

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check if editorconfig exists
        if: ${{ hashFiles('.editorconfig') == '' }}
        run: exit 'editorconfig does not exist.'

      - name: Add checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run checker
        run: editorconfig-checker

      - name: Run Python linter - pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      - name: Run Python linter - black
        uses: psf/black@stable

      - name: Run markdown linter
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: README.md

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        working-directory: ./app
        run: python -m pip install -r requirements.txt

      - name: Run tests
        working-directory: ./app
        run: python -m unittest app_test.py

  security:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-smells:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

  review-security-issues:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v3

      - name: Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dvdty/github-actions-practice:${{ github.sha }}
