name: ci

on:
  push:
    branches: ['github-actions-practice']

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check-editorconfig
        if: ${{ hashFiles('assets/') == '' }}
        run: exit 1

      - name: pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

      - name: black
        uses: psf/black@stable

      - name: markdown
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: README.md

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install app/requirements.txt

  security:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
